#!/bin/bash

rm -f CMakeCache.txt

SOURCE=$HOME/develop/Jali

export ARCHOS="`uname -m`_`uname -s`"

# modify the paths that point to the location of the
# installation directories below

cmake \
  -C /research/rao/Jali-tpl/share/cmake/Jali-tpl-config.cmake \
  -D CMAKE_BUILD_TYPE=Debug \
  -D CMAKE_INSTALL_PREFIX:FILEPATH=/research/rao/Jali-install \
  -D HDF5_NO_SYSTEM_PATHS:BOOL=TRUE \
  -D BOOST_ROOT:FILEPATH=/research/rao/Jali-tpl \
  -D ENABLE_MSTK_Mesh:BOOL=TRUE \
  -D ENABLE_STK_Mesh:BOOL=FALSE \
  -D ENABLE_MOAB_Mesh:BOOL=FALSE \
  ${SOURCE} 

