#!/bin/sh


SOURCE=$HOME/develop/Jali
INSTALL_PREFIX=/research/rao/Jali-tpl

rm -f CMakeCache.txt
rm -fr $INSTALL_PREFIX

cmake \
-D CMAKE_C_COMPILER=`which mpicc` \
-D CMAKE_CXX_COMPILER=`which mpiCC` \
-D CMAKE_Fortran_COMPILER=`which mpif90` \
-D DISABLE_EXTERNAL_DOWNLOAD:BOOL=TRUE \
-D TPL_DOWNLOAD_DIR:PATH=$HOME/develop/ASCEM/tpl-downloads \
-D TPL_INSTALL_PREFIX=$INSTALL_PREFIX \
$SOURCE/config/SuperBuild/ 

