# Copyright (c) 2019, Triad National Security, LLC
# All rights reserved.

# Copyright 2019. Triad National Security, LLC. This software was
# produced under U.S. Government contract 89233218CNA000001 for Los
# Alamos National Laboratory (LANL), which is operated by Triad
# National Security, LLC for the U.S. Department of Energy. 
# All rights in the program are reserved by Triad National Security,
# LLC, and the U.S. Department of Energy/National Nuclear Security
# Administration. The Government is granted for itself and others acting
# on its behalf a nonexclusive, paid-up, irrevocable worldwide license
# in this material to reproduce, prepare derivative works, distribute
# copies to the public, perform publicly and display publicly, and to
# permit others to do so
 
# 
# This is open source software distributed under the 3-clause BSD license.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of Triad National Security, LLC, Los Alamos
#    National Laboratory, LANL, the U.S. Government, nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
# 
 
# THIS SOFTWARE IS PROVIDED BY TRIAD NATIONAL SECURITY, LLC AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
# TRIAD NATIONAL SECURITY, LLC OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

include(CMakeParseArguments)
include(PrintVariable)

function(Create_Imported_Target_File output)

  # --- Macros for this function 
  macro(WRITE_HEADER)
    file(WRITE ${output}  "# Imported Library Targets\n")
    file(APPEND ${output} "# Generated by CMake ${CMAKE_VERSION}\n")
  endmacro(WRITE_HEADER)

  macro(WRITE_TARGET target type)
    file(APPEND ${output} "\n# Import target \"${target}\"\n")
    file(APPEND ${output} "ADD_LIBRARY(${target} ${type} IMPORTED)\n")
  endmacro(WRITE_TARGET)

  macro(WRITE_TARGET_PROPERTIES target)

    set(_imported_target_properties 
         IMPORTED_LOCATION
	 IMPORTED_LINK_INTERFACE_LANGUAGES
	 IMPORTED_LINK_INTERFACE_LIBRARIES)

    set(_write_string "SET_TARGET_PROPERTIES(${target} PROPERTIES\n")

    foreach(_prop_name ${_imported_target_properties})
      get_target_property(_prop ${target} ${_prop_name})
      if ( _prop )
	set(_write_string "${_write_string}  ${_prop_name} \"${_prop}\"\n")
      endif()
    endforeach()
    set(_write_string "${_write_string})\n")

    file(APPEND ${output} "${_write_string}")

  endmacro(WRITE_TARGET_PROPERTIES)

  # --- Begin function MAIN 
  write_header()

  # --- Loop through each library type
  set(_lib_types UNKNOWN SHARED STATIC)
  foreach( _type ${_lib_types} )
    get_property(_libs GLOBAL PROPERTY IMPORTED_${_type}_LIBRARIES)
    foreach ( _lib ${_libs} )
      write_target(${_lib} ${_type})
      write_target_properties(${_lib})
    endforeach()
  endforeach()  

endfunction(Create_Imported_Target_File )
